Initial commit
strizr/kontent-model-visualizer pull request #1
Opened 2022-09-30 09:47 UTC by strizr

2022-10-03 09:36 UTC, strizr commented
TODO: Readme update

2022-10-05 18:28 UTC, Simply007 requested changes
Just a couple of notes. Overall it is OK and well readable.

2022-10-05 18:28 UTC, Simply007 commented on src/components/visualizer/shared/NetworkToolbar.vue
> +        </v-tooltip>-->
Remove the comment

2022-10-05 18:28 UTC, Simply007 commented on src/components/visualizer/shared/NetworkToolbar.vue
> +            <v-btn v-show="buttons.fullscreen" class="ma-1" text icon @click="fullscreen">
still visible even if on fullscreen

2022-10-05 18:28 UTC, Simply007 commented on src/components/visualizer/shared/NetworkToolbar.vue
> +    save() {
Unused method

2022-10-05 18:28 UTC, Simply007 commented on src/components/visualizer/shared/KontentNetwork.vue
> +    <network-toolbar :buttons="buttons" @fit="fit" @save="save"></network-toolbar>
I don!T see fit and save buttons in UI - if they are not used, remove them as well as Saving Dialog

2022-10-05 18:28 UTC, Simply007 commented on src/components/visualizer/detail/ModelElements.vue
> +      switch (type) {
DO we want to add SubPages element?

2022-10-05 18:28 UTC, Simply007 commented on src/components/visualizer/detail/ModelElements.vue
> +      switch (type) {
The cases are probably not probably well defined.

2022-10-05 18:28 UTC, Simply007 commented on src/components/visualizer/overview/SelectedNodeDetail.vue
> +                        @click="focus(item.id)"
I would add at least tooltip, what it does when you click on it.

2022-10-05 18:28 UTC, Simply007 commented on src/components/visualizer/overview/SelectedNodeDetail.vue
> +                            >{{prop}}</v-chip>
Looks like clicking does something else - but does also focus.

2022-10-13 11:56 UTC, strizr commented on src/components/visualizer/shared/KontentNetwork.vue
> +    <network-toolbar :buttons="buttons" @fit="fit" @save="save"></network-toolbar>
removing save, fit is visible and usable

2022-10-14 11:33 UTC, merged